In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../data/raw/student_dropout_dataset_v3.csv")

In [13]:
df

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,No,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,No,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,No,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,No,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,No,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.9,Female,42286.0,No,4.620000,92.0,0,10.0,Yes,Yes,5.500000,1.60,0.99,0.97,Year 2,Arts,Bachelor,0
9996,9997,17.0,Female,61103.0,Yes,2.870000,75.2,3,32.4,No,Yes,6.700000,3.09,3.09,3.09,Year 1,Business,Master,1
9997,9998,19.4,Male,25000.0,Yes,4.730000,74.9,4,25.4,No,No,3.500000,3.45,3.37,3.43,Year 4,Business,Bachelor,0
9998,9999,22.1,Female,40302.0,Yes,5.850000,74.2,1,5.0,No,Yes,6.200000,3.35,3.34,3.34,Year 1,CS,High School,0
9999,10000,22.4,Female,76796.0,Yes,4.950000,83.7,1,15.5,Yes,No,7.900000,2.17,2.20,2.20,Year 1,Arts,Master,0

In [8]:
df['Age']=df['Age'].round().astype(int)

In [9]:
df.dtypes

Student_ID                 int64
Age                        int64
Gender                    object
Family_Income            float64
Internet_Access           object
Study_Hours_per_Day      float64
Attendance_Rate          float64
Assignment_Delay_Days      int64
Travel_Time_Minutes      float64
Part_Time_Job             object
Scholarship               object
Stress_Index             float64
GPA                      float64
Semester_GPA             float64
CGPA                     float64
Semester                  object
Department                object
Parental_Education        object
Dropout                    int64
dtype: object

In [10]:
df['Family_Income'].fillna(df['Family_Income'].median(),inplace=True)

In [11]:
df['Study_Hours_per_Day'].fillna(df['Study_Hours_per_Day'].mean(), inplace=True)

In [12]:
df['Stress_Index'].fillna(df['Stress_Index'].mean(), inplace=True)

In [13]:
df['Parental_Education'].fillna(df['Parental_Education'].mode()[0], inplace=True)

### Observation
- Family_Income was imputed using median due to strong positive skew.
- Study_Hours_per_Day and Stress_Index were imputed using mean as their distributions were symmetric.
- Parental_Education was imputed using mode to preserve categorical balance.
- No missing values remain after treatment.

In [14]:
outlier_checking_cols = [
    'Family_Income',
    'Study_Hours_per_Day',
    'Travel_Time_Minutes'
]

In [15]:
for col in outlier_checking_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col} → {len(outliers)} outliers")

Family_Income → 683 outliers
Study_Hours_per_Day → 138 outliers
Travel_Time_Minutes → 25 outliers

### Outlier Detection Observations

- Most detected outliers are distribution-driven rather than data errors.

- Family_Income shows high outlier count due to right-skewed income distribution.

- Other variables show realistic extreme values and were retained.

- No outlier removal performed to preserve real-world variability.

- Outliers were retained since removal could distort behavioral patterns and model performance.

In [17]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Student_ID,10000.0,NaN,NaN,NaN,5000.5,2886.89568,1.0,2500.75,5000.5,7500.25,10000.0
Age,10000.0,NaN,NaN,NaN,21.0265,2.160015,17.0,20.0,21.0,22.0,30.0
Gender,10000,2,Female,5011,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Family_Income,10000.0,NaN,NaN,NaN,37945.4101,20065.697032,25000.0,25000.0,29740.5,43361.75,316601.0
Internet_Access,10000,2,Yes,8769,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Study_Hours_per_Day,10000.0,NaN,NaN,NaN,4.014592,1.262645,0.5,3.21,4.014592,4.81,8.98
Attendance_Rate,10000.0,NaN,NaN,NaN,81.73683,8.22093,38.2,76.4,81.8,87.3,100.0
Assignment_Delay_Days,10000.0,NaN,NaN,NaN,1.7997,1.344307,0.0,1.0,2.0,3.0,8.0
Travel_Time_Minutes,10000.0,NaN,NaN,NaN,30.17926,11.91887,5.0,21.9,30.2,38.4,74.9
Part_Time_Job,10000,2,No,5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Scholarship,10000,2,No,6489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stress_Index,10000.0,NaN,NaN,NaN,5.507147,1.721231,1.0,4.4,5.507147,6.6,10.0
GPA,10000.0,NaN,NaN,NaN,2.30844,1.061717,0.0,1.55,2.35,3.12,4.0
Semester_GPA,10000.0,NaN,NaN,NaN,2.300057,1.074407,0.0,1.52,2.35,3.15,4.0
CGPA,10000.0,NaN,NaN,NaN,2.298761,1.072555,0.0,1.52,2.35,3.15,4.0
Semester,10000,4,Year 4,2536,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Department,10000,5,Science,2061,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Parental_Education,10000,4,Bachelor,4460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dropout,10000.0,NaN,NaN,NaN,0.2354,0.42427,0.0,0.0,0.0,0.0,1.0

In [38]:
df.to_csv("cleaned_day2.csv", index=False)

In [39]:
df

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,No,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,21,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,No,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,No,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,No,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,No,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,24,Female,42286.0,No,4.620000,92.0,0,10.0,Yes,Yes,5.500000,1.60,0.99,0.97,Year 2,Arts,Bachelor,0
9996,9997,17,Female,61103.0,Yes,2.870000,75.2,3,32.4,No,Yes,6.700000,3.09,3.09,3.09,Year 1,Business,Master,1
9997,9998,19,Male,25000.0,Yes,4.730000,74.9,4,25.4,No,No,3.500000,3.45,3.37,3.43,Year 4,Business,Bachelor,0
9998,9999,22,Female,40302.0,Yes,5.850000,74.2,1,5.0,No,Yes,6.200000,3.35,3.34,3.34,Year 1,CS,High School,0
9999,10000,22,Female,76796.0,Yes,4.950000,83.7,1,15.5,Yes,No,7.900000,2.17,2.20,2.20,Year 1,Arts,Master,0