In [10]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind
from scipy.stats import f_oneway

In [2]:
df = pd.read_csv("../data/interim/cleaned_day2.csv")

In [3]:
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,No,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,21,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,No,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,No,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,No,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,No,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0

## Two Sample Independent T-test (GPA)

Checking whether if there is any mean difference between GPA of dropout students and non-dropout students.

- Null hypothesis(H0):there is no difference between GPA of dropout students and non-dropout students.
- Alternative hypothesis(H1):There is a significant difference between GPA of dropout students and non-dropout students.

In [9]:
dropout_yes = df[df["Dropout"] == 1]["GPA"]
dropout_no = df[df["Dropout"] == 0]["GPA"]

t_stat, p_value = ttest_ind(dropout_yes, dropout_no)

print("T-stat:", t_stat)
print("P-value:", p_value)

if p_value <=0.05:
  print('There is significance difference between the mean GPA between dropout and non dropout.')
else:
  print('There is no difference in GPA mean between dropout and non dropout.')

T-stat: -51.8516418453324
P-value: 0.0
There is significance difference between the mean GPA between dropout and non dropout.

## Interpretation
- Result:The p-value is extremely small (p < 0.05), which means the difference is statistically significant.
- conclusion:GPA has a strong relationship with dropout.

# Two Sample Independent T-test (Stress Index)

Checking whether if there is any mean difference between GPA of dropout students and non-dropout students.

- Null hypothesis(H0): There is no difference between stress level of dropout students and non-dropout students.
- Alternative hypothesis(H1): There is a significant difference between stress level of dropout students and non-dropout students

In [15]:
stress_dropout = df[df["Dropout"] == 1]["Stress_Index"]
stress_no_dropout = df[df["Dropout"] == 0]["Stress_Index"]
t_stat, p_value = ttest_ind(stress_dropout,stress_no_dropout)

print("T-stat:", t_stat)
print("P-value:", p_value)

if p_value <=0.05:
  print('There is significance difference between the mean stress level between dropout and non dropout.')
else:
  print('There is no difference in mean stress level between dropout and non dropout.')

T-stat: 25.74641416818363
P-value: 1.3589597274737893e-141
There is significance difference between the mean stress level between dropout and non dropout.

## Interpretation
- The p-value is far below 0.05, so we reject the null hypothesis.
- Mean stress level for students who dropped out is significantly higher than for those who didn’t drop.
- Conclusion: Higher stress levels are strongly associated with increased dropout risk.

## Two Sample Independent T-test (Attendence Rate)

Checking whether if there is any mean difference between attendence of dropout students and non-dropout students.

- Null hypothesis(H0): There is no difference between attedence of dropout students and non-dropout students.
- Alternative hypothesis(H1): There is a significant difference between attendence of dropout students and non-dropout students.

In [23]:
dropout = df[df["Dropout"] == 1]["Attendance_Rate"]
no_dropout = df[df["Dropout"] == 0]["Attendance_Rate"]
t_stat, p_value = ttest_ind(dropout,no_dropout)

print("T-stat:", t_stat)
print("P-value:", p_value)

if p_value <=0.05:
  print('There is significance difference between the mean attendence between dropout and non dropout.')
else:
  print('There is no difference in mean attendence between dropout and non dropout.')

T-stat: -16.575435235696997
P-value: 6.786877659568078e-61
There is significance difference between the mean attendence between dropout and non dropout.

## Interpretation

- The p-value is below 0.05, so we reject the null hypothesis.
- Attendance rate for students who dropped out is significantly lower than for those who didn’t drop.

## ANOVA Test (GPA vs Department)

To check if the mean GPA differs across departments.

In [14]:
groups = [group['GPA'].values for name, group in df.groupby('Department')]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("There is a statistically significant difference in mean GPA across departments.")
else:
    print("There is no statistically significant difference in mean GPA across departments.")

F-statistic: 0.9959698709669378
P-value: 0.4082456335654021
There is no statistically significant difference in mean GPA across departments.

## Interpretation
- The p-value is greater than 0.05.
- we fail to reject the null hypothesis.
- Conclusion: there is no statistically significant difference in mean GPA among the departments.

# Feature Engineering

## Study Efficiency
- Study efficiency is calculated for how much effort a student puts in for each unit of their GPA.
- Higher values might indicate less efficiency or greater difficulty.
-  this tells how many study hours are required to produce one single point of GPA.

In [17]:
df["Study_Efficiency"] = df["Study_Hours_per_Day"] / df["GPA"]
df

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout,Study_Efficiency
0,1,22,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,No,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0,3.500000
1,2,21,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,No,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1,3.359375
2,3,22,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,No,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0,2.619048
3,4,24,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,No,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1,2.255389
4,5,20,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,No,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0,2.831081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,24,Female,42286.0,No,4.620000,92.0,0,10.0,Yes,Yes,5.500000,1.60,0.99,0.97,Year 2,Arts,Bachelor,0,2.887500
9996,9997,17,Female,61103.0,Yes,2.870000,75.2,3,32.4,No,Yes,6.700000,3.09,3.09,3.09,Year 1,Business,Master,1,0.928803
9997,9998,19,Male,25000.0,Yes,4.730000,74.9,4,25.4,No,No,3.500000,3.45,3.37,3.43,Year 4,Business,Bachelor,0,1.371014
9998,9999,22,Female,40302.0,Yes,5.850000,74.2,1,5.0,No,Yes,6.200000,3.35,3.34,3.34,Year 1,CS,High School,0,1.746269
9999,10000,22,Female,76796.0,Yes,4.950000,83.7,1,15.5,Yes,No,7.900000,2.17,2.20,2.20,Year 1,Arts,Master,0,2.281106

## Academic Habits Score

- Measures student engagement and compliance by dividing the Attendance_Rate by the Assignment_Delay_Days plus 1.
- A higher score indicates better attendance and fewer delays.

In [18]:
df["Academic_Habits_Score"]=df['Attendance_Rate'] / (df['Assignment_Delay_Days'] + 1)
df

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,...,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout,Study_Efficiency,Academic_Habits_Score
0,1,22,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,...,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0,3.500000,28.700000
1,2,21,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,...,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1,3.359375,22.666667
2,3,22,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,...,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0,2.619048,70.900000
3,4,24,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,...,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1,2.255389,27.400000
4,5,20,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,...,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0,2.831081,37.850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,24,Female,42286.0,No,4.620000,92.0,0,10.0,Yes,...,5.500000,1.60,0.99,0.97,Year 2,Arts,Bachelor,0,2.887500,92.000000
9996,9997,17,Female,61103.0,Yes,2.870000,75.2,3,32.4,No,...,6.700000,3.09,3.09,3.09,Year 1,Business,Master,1,0.928803,18.800000
9997,9998,19,Male,25000.0,Yes,4.730000,74.9,4,25.4,No,...,3.500000,3.45,3.37,3.43,Year 4,Business,Bachelor,0,1.371014,14.980000
9998,9999,22,Female,40302.0,Yes,5.850000,74.2,1,5.0,No,...,6.200000,3.35,3.34,3.34,Year 1,CS,High School,0,1.746269,37.100000
9999,10000,22,Female,76796.0,Yes,4.950000,83.7,1,15.5,Yes,...,7.900000,2.17,2.20,2.20,Year 1,Arts,Master,0,2.281106,41.850000

## CGPA Improvement

- This measures the difference between a student's current semester performance and their cumulative performance over time.

### Interpretation:

-Positive Value: The student's grades are improving.

-Negative Value: The student's grades are declining.

In [19]:
df['CGPA_Improvement']=df['Semester_GPA']-df['CGPA']
df

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,...,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout,Study_Efficiency,Academic_Habits_Score,CGPA_Improvement
0,1,22,Male,25000.0,Yes,3.360000,86.1,2,20.4,Yes,...,0.96,0.90,0.90,Year 1,Arts,High School,0,3.500000,28.700000,0.00
1,2,21,Male,25000.0,Yes,4.300000,68.0,2,44.0,No,...,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1,3.359375,22.666667,0.01
2,3,22,Male,40183.0,Yes,4.400000,70.9,0,48.9,Yes,...,1.68,1.32,1.32,Year 1,Arts,Master,0,2.619048,70.900000,0.00
3,4,24,Male,29740.5,Yes,4.014592,82.2,2,38.6,No,...,1.78,1.77,1.77,Year 1,CS,High School,1,2.255389,27.400000,0.00
4,5,20,Female,25319.0,Yes,4.190000,75.7,1,23.0,No,...,1.48,0.91,0.87,Year 4,Business,Bachelor,0,2.831081,37.850000,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,24,Female,42286.0,No,4.620000,92.0,0,10.0,Yes,...,1.60,0.99,0.97,Year 2,Arts,Bachelor,0,2.887500,92.000000,0.02
9996,9997,17,Female,61103.0,Yes,2.870000,75.2,3,32.4,No,...,3.09,3.09,3.09,Year 1,Business,Master,1,0.928803,18.800000,0.00
9997,9998,19,Male,25000.0,Yes,4.730000,74.9,4,25.4,No,...,3.45,3.37,3.43,Year 4,Business,Bachelor,0,1.371014,14.980000,-0.06
9998,9999,22,Female,40302.0,Yes,5.850000,74.2,1,5.0,No,...,3.35,3.34,3.34,Year 1,CS,High School,0,1.746269,37.100000,0.00
9999,10000,22,Female,76796.0,Yes,4.950000,83.7,1,15.5,Yes,...,2.17,2.20,2.20,Year 1,Arts,Master,0,2.281106,41.850000,0.00

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  int64
 2   Gender                 10000 non-null  object
 3   Family_Income          10000 non-null  float64
 4   Internet_Access        10000 non-null  object
 5   Study_Hours_per_Day    10000 non-null  float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  object
 10  Scholarship            10000 non-null  object
 11  Stress_Index           10000 non-null  float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  object
 16  Department             10000 non-null  object
 17  Parental_Education     10000 non-null  object
 18  Dropout                10000 non-null  int64
 19  Study_Efficiency       10000 non-null  float64
 20  Academic_Habits_Score  10000 non-null  float64
 21  CGPA_Improvement       10000 non-null  float64
dtypes: float64(11), int64(4), object(7)
memory usage: 1.7+ MB

In [21]:
df.to_csv("final_cleaned_day4.csv", index=False)